version: '3.8'

services:
  odoo:
    image: odoo:16.0
    container_name: odoo
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8069:8069"
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo_data:/var/lib/odoo
    networks:
      - odoo-network

  postgres:
    image: postgres:15
    container_name: postgres-odoo
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - odoo-network

volumes:
  postgres_data:
  odoo_data:

networks:
  odoo-network:
    driver: bridge